### ISSUE TITLE
Is it possible to run it only with expression and metadata?

### ISSUE THREAD

**Issue by josruirod** [flatironinstitute/inferelator_sc#36]
Hi, 
I understood from the readme that this could be run only with the regulators and the expression data, even if the performarnce would be "extremely poor". I would like to test that, but I'm getting the error "No gold standard or priors have been provided". Are these required in all cases?
Thanks

**Comment by asistradition** [comment]
Yep, although it will raise an error (as you've noticed) if you don't set a couple of flags to suppress the error. 

```
from inferelator import inferelator_workflow

worker = inferelator_workflow(regression="elasticnet", workflow="tfa")
worker.set_network_data_flags(use_no_prior=True, use_no_gold_standard=True)
```


This should work. Let me know if there are any problems.

**Comment by josruirod** [comment]
Sorry i missed that. It's now working good. Thanks
