### ISSUE TITLE
Result object (why max recall is not 1?)

### ISSUE THREAD

**Issue by frankligy** [flatironinstitute/inferelator_sc#44]
Hi,

I apologize if that's a stupid question, but when I applied inferelator to one of my dataset, I got the `network.tsv` file as below (only shown the last several lines ranked in descending order by `combined_confidences`, also I redacted the target and regulator):

<img width="1009" alt="Screen Shot 2021-07-01 at 4 21 43 PM" src="https://user-images.githubusercontent.com/59619831/124185068-72b7fd00-da88-11eb-9ad4-4aedc60f3f48.png">

My question is, why the recall column only ends at 0.1 or so? In my understanding, recall means the proportion of 1 in gold standard that has been predicted out in the model, so as the cutoff of `combined_confidences` keeps decreasing, the recall should eventually reach 1, is it correct?

Much appreciated for your clarifications,
Frank

**Comment by asistradition** [comment]
The network output for the inferelator is thresholded (it's a pretty soft threshold on the theory that most people will want to pick a cutoff of their own for edges to include in a network based on some preferred metric or criteria). There are (assuming you're working in a mammalian system) somewhere between 20m and 100m possible network edges, depending on how many genes and TFs are included, so listing all of the possible edges in a long table (even the ones with no evidence) crashes excel a lot.

The reason that the recall stops at 0.1 is that 90% of the edges in the scoring network are not among the 147k edges in this edge table. They'll all be accounted for basically as 'tied with no evidence', and calculated into the result curves accordingly. You can get the confidences for every possible edge from the `combined_confidences.tsv.gz` file if you need them.
