### ISSUE TITLE
Metadata format

### ISSUE THREAD

**Issue by poorvam** [flatironinstitute/inferelator_sc#55]
Hi,

I am using nonbraching metadata (it has 3 columns only) format when running inferelator (https://inferelator.readthedocs.io/en/latest/tutorial.html)

But the program prints below, is there a function to let inferelator use nonbraching format?

  Inferelator MPControl using engine multiprocessing
 Loading expression data file [XXX]_normCounts.tsv
 Loading metadata file phenotype.tsv
 Loaded [XXX]_normCounts.tsv:
....
....
Skipping metadata because parsing requires missing columns: Index(['del.t', 'isTs', 'prevCol'], dtype='object')

Thanks,
Poorva

**Comment by asistradition** [comment]
If you've created a workflow (e.g. `inferer = inferelator_workflow(regression="bbsr", workflow="tfa")`), you can set the metadata format with `inferer.set_file_properties(metadata_handler='nonbranching')`.
