### ISSUE TITLE
Time series

### ISSUE THREAD

**Issue by torgeihv** [flatironinstitute/inferelator_sc#57]
I have a time series expression data set and have specified the consecutive time points in the meta data:

isTs	is1stLast	prevCol	del.t	condName
1	TRUE	f	NA	1	T1.1
2	TRUE	m	T1.1	1	T1.2
3	TRUE	m	T1.2	1	T1.3
4	TRUE	m	T1.3	1	T1.4
...

When I ask to get the TFA data printed out with "worker.set_tfa(tfa_output_file = 'tfa.tsv'", I get the data with features T1.2-T1.1, etc. 

Since I would like to compare expression data to TF activity data for some selected regulators, I was wondering if it is possible to print the TFA data using the original features (T1.1, T1.2)?

**Comment by asistradition** [comment]
The output is correct - when using time series data, the TFA incorporates the difference between timepoints. As a result, if you have N timepoints in a series, you'd have N-1 timepoints in the TFA, and the names in the output TFA matrix reflect that.

You can disable this with `worker.set_design_settings(timecourse_response_driver=False)`, which will treat every timepoint as separate and generate TFA values for each of them individually.
